### ISSUE TITLE
PGTitles, CMBAATitles: redundant title type fields

### ISSUE THREAD

**Issue by rhao** [american-art/cbm#1]
The TitleTypeID, TitleType and DisplayOrder fields all seem redundant. I used TitleType and ignored the other two. Let me know if this is incorrect or if there is a distinction between the 3 fields!

**Comment by shanerichey** [comment]
From a database perspective TitleTypeID, TitleType, and Display Order aren’t redundant per se. TitleType is the string denoting the type of title (Primary, Alternate, Group, etc.), and TitleTypeID is a shorthand to denote which string from TitleType is being used. Display Order denotes what order multiple titles for the same object are displayed in in TMS. For this project I agree with only using TitleType for the moment. I can see how the ID is irrelevant and display order won’t apply. As long as “Primary Titles” are listed first. I wouldn’t want people to think an Alternate Title is the Primary Title.
