### ISSUE TITLE
CBMAAObjects:DateBegin and DateEnd

### ISSUE THREAD

**Issue by steads** [american-art/cbm#10]
DateBegin and DateEnd: The mapping shows the path as 
E22 ->P108i ->E12 [Object] ->P4 ->E52   ->P82a ->E61 [DateBegin]
->P82b ->E61 [DateEnd]
This would be correct if the Dated field was about the production of the object in the collection. However, in at least one case the Dated field and its interpretation in the DateBegin and DateEnd fields are not consistent with this interpretation. For instance:-
2014.19 1947-1953, cast 1990    1947    1953

This suggests the item in the collection was cast in 1990 from a mould that was created between 1947 and 1953 but the DateBegin and DateEnd are for an object created between 1947 and 1953.
There are also inconsistencies in how the boundaries have been set for circa dates (noted by a “ca.” in the Dated field) and date ranges and circa date ranges. This should probably be addressed during data cleaning/enrichment.
I would therefore be very cautious of these fields until a complete analysis of the Dated field has been completed as in several cases they are probably associated with events other than the production of the object in the collection. 
A final note the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by ghost** [comment]
So the issue you raise about an object cast in 1990 but based on a mould from 1947-1953 addresses a shortfall in the way dates are handled. The decision has to be made for the DateBegin/DateEnd (which are functionally search dates). Do you do 1947-1990 or 1947-1953 or 1990 since you only have two fields to choose from. 1947-1990 seems inaccurate to me because 1954-1989 wouldn't apply to the object. Essentially I don't know how much cleaning we can do in that regard.

**Comment by steads** [comment]
The reality is that there are 2 objects: the mould and the casting in the collection. You know that the mould existed so you could you document it without making the statement that CBM owns it. Or you could ignore it and just document the object you have in the collection. The object in the collection has a date of 1990.
