### ISSUE TITLE
CBMAAObjects:Medium

### ISSUE THREAD

**Issue by steads** [american-art/cbm#11]
Medium: Fields like this are a perpetual problem. It is a mishmash of many different things lumped together into one field. It is a mixture of technique, mostly general but some specifics, and material. To deal with it completely would require a full analysis of each different unique entry string so that they can be divided into those elements that are E29 Design or Procedure (for specific documented techniques), E55 Type (for general techniques) and E57 Materials. Also the relationship needs to be established so that the correct property is used to connect things. Materials that become part of the object use P45 whereas materials that are just used during modification/production would use P126 employed (was employed in). If the resources are available to do this analysis then great, if not then treat it as a simple E55 Type. 
E22 -> P2 ->E55 (Medium).

**Comment by ghost** [comment]
I think we'll just have to leave it as an E55 Type.
