### ISSUE TITLE
CBMAAObjects:Dimensions

### ISSUE THREAD

**Issue by steads** [american-art/cbm#12]
Dimensions: There is a lot of variability in the format and also probably in the intended meaning of the content of this field. With analysis and processing 4 to 10 instances of E54 Dimension could be extracted from each entry in this field: metric and imperial; length, breadth and, for 3D works, depth plus the same including the frame. Some of the text flags present in the field might be used to qualify (with an E55 Type) the nature of an associated E16 Measurement. There are also dimensions of other objects like the album the object is in and the size of crate that presumable it ships in. Else treat as a string:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Dimensions Statement}

**Comment by ghost** [comment]
We will discuss the possibility of separating out dimensions into each of it's constituent parts (H x W x D).
