### ISSUE TITLE
CBMAAObjects:CreditLine

### ISSUE THREAD

**Issue by steads** [american-art/cbm#13]
CreditLine: Doesn’t seem to have a mapping. There are hidden events in many of the statements that could, with further analysis, produce a number of instances of E7 Activity and instances of E39 Actor with P14.1 roles in the instances of E7 Activity. If the resources are not available then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Credit Line Statement}

**Comment by ghost** [comment]
Credit absolutely needs to be mapped and we won't be able to separate it out into constituent parts.
