### ISSUE TITLE
CBMAAObjects:Inscribed

### ISSUE THREAD

**Issue by steads** [american-art/cbm#16]
Inscribed: The mapping is correct though I would add P3.1 has type {Details of Inscription statement}. It is suggested in the CRM that the text itself be documented using P3 has note: E62 String. This text though contains documentation of the location etc as well as the text therefore, if the source and history of this statement is documented, it could be regarded as an instance of E31 Document connected via P70 documents (is documented in) to the instance of E34 Inscription. 
At least one entry looks more like an instance of E37 Mark:-
2007.21 verso: [Charles Kurtz collection stamp]

**Comment by ghost** [comment]
I fixed 2007.21 - will re-upload the data
