### ISSUE TITLE
CBMAAObjects:Markings

### ISSUE THREAD

**Issue by steads** [american-art/cbm#17]
Markings: The mapping is correct though I would add P3.1 has type {Details of Markngs statement}. If the source and history of this statement is documented then it could be regarded as an instance of E31 Document connected via P70 documents (is documented in) to the instance of E37 Mark.
There are several examples where the entries look more like instances of E34 Inscription for example:-
2006.61 l.l.: PAINTED BY G.C. BINGHAM, ESQ.
l.r: ENGRAVED BY T. DONEY
l.r.: PRINTED BY POWELL & CO.
l.c.: THE JOLLY FLAT BOAT MEN. / From the Original painting distributed by the American Art Union in 1847 / Published exclusively for the Members of that Year
l.c.: Entered according to Act of Congress in the year 1847 by the American Art Union in the Clerk's Office of the U.S. District Court for the Southern District of New York

**Comment by ghost** [comment]
Some of these might possibly be inscriptions, some possibly might be marks. Not all people who enter data note the way in which the marks/inscriptions/signatures are applied to the object. Marks are typically labels or stamps.

**Comment by steads** [comment]
This should be cleaned so the correct data is in the correct field.
