### ISSUE TITLE
CBMAAObjects:Provenance

### ISSUE THREAD

**Issue by steads** [american-art/cbm#18]
Provenance: E22 ->P129i -> E33 ->P3 ->E62 is incorrect. There are many hidden events in these statements that could, with further analysis, produce many instances of E10 Transfer of Custody, E8 Acquisition, E9 Move and probably some E7 Activity and instances of E39 Actor with P22, P23, P28, P29 and P14.1 roles in them. If the resources are not available then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Provenance Statement}

**Comment by ghost** [comment]
The resources are not available to split out Provenance into each of its parts.
