### ISSUE TITLE
CBMAAObjects:Exhibitions

### ISSUE THREAD

**Issue by steads** [american-art/cbm#19]
Exhibitions: The current mapping to a single instance of E7 Activity and corresponding E41 Appellation does not reflect the actual data. There are many hidden events in these statements that could, with further analysis, produce many instances of E7 Activity, their appellations and involved instances of E39 Actor. If the resources are not available then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Exhibitions Statement}

**Comment by ghost** [comment]
The resources are not available to split out exhibitions into each of its parts.

**Comment by VladimirAlexiev** [comment]
@JMunro01 That's not true. Consider https://github.com/american-art/cbm/blob/master/CBMAA%20LOD%20v2/LOD%20CBMAA%20Exhibitions.csv, eg rows 3-7 say:
- object 21 was at exhibition 33 Art in America: 300 Years of Innovation.
- That exhibition lasted from 2007-02-10 to 2008-04-27
- That exhibition visited 4 venues: Pushkin Museum of Fine Arts, Shanghai Museum, National Art Museum of China, Guggenheim Museum Bilbao
- Those sub-exhibitions lasted in their own sub-intervals
- Those sub-exhibitions were organized by particular Venue Constituents

BTW, there are two files. Can you say which one is more up to date?
- CBMAA_Exhibitions/LOD CBMAA Exhibitions.csv (smaller)
- CBMAA LOD v2/LOD CBMAA Exhibitions.csv (bigger)

**Comment by ghost** [comment]
@VladimirAlexiev v2 is newer. And yea, I wasn't sure what was meant by splitting it out, I mean to me its already split out. We have the object, the overall exhibition, the exhibition dates, and the venue and venue dates.
