### ISSUE TITLE
PGConstituents/CBMAAConstituents: unused fields okay?

### ISSUE THREAD

**Issue by rhao** [american-art/cbm#2]
I did not use the ConXrefID, DisplayName, AlphaSort, NameTitle, RoleTypeID, RoleType, RoleID, or DataDate fields. Is this acceptable? The name fields seemed to be covered by the first/middle/last name fields, and the role-based fields seemed to be covered by the Role field.

**Comment by shanerichey** [comment]
For Constituents the answer is much the same as the above. I can see how FirstName, MiddleName, and LastName supersede the Alpha Sort or DisplayName. I’m fine with what they’ve done provided the First, Middle, and Last Names are linked together in some fashion.
