### ISSUE TITLE
CBMAATitles:DisplayOrder

### ISSUE THREAD

**Issue by steads** [american-art/cbm#27]
DisplayOrder: This is a system implementation instruction and as such has no need for a mapping. However if the meaning in this field is important outside the system then additional instances of E35 Title should be instantiated. For example:-
2005.21     ->P102 E35 {Burlesque #2}
        ->P102 E35 {Vaudeville}
->P102 E35 {Burlesque #2: Vaudeville}
Note that I have chosen to use “: “ to separate the two Titles as I concatenate them but any characters could be used. It might also be that the concatenated version is no longer considered an E35 Title in which case you could move up to an E41 Appellation. In this case the correct property link would be P1 is identified by (identifies).

**Comment by ghost** [comment]
Display Order would stipulate which title should appear first. I don't know if that applies to mapping at all.
