### ISSUE TITLE
CBMAAExhibitions:ExhibBeginISODate

### ISSUE THREAD

**Issue by steads** [american-art/cbm#34]
ExhibBeginISODate: These are not in ISO format (http://imgs.xkcd.com/comics/iso_8601.png). 
The full mapping should then be:-
E22     ->P16i ->E7 [Exhibition] ->P4 ->E52 ->P82a ->E61 [ExhibBeginISODate]
    ->P16.1 ->E55 {Exhibit}
A final note the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by ghost** [comment]
Our database mistakenly calls this table an ISO table. The dates are correct as is, though yes they are not ISO format.
