### ISSUE TITLE
CBMAAExhibitions:ExhibEndISODate

### ISSUE THREAD

**Issue by steads** [american-art/cbm#35]
ExhibEndISODate: These are not in ISO format (http://imgs.xkcd.com/comics/iso_8601.png).
There are several dates which would seem to be planned end dates (dates in late 2016-2017). These have a different nature to the end dates that are historical facts but might be useful for some purposes as modelled. However the data will introduce problems in the future as it will give rise to two versions of history: the planned and the actual and no way of knowing from the data which is which. It would be better to select a time primitive with a concept of ongoing at the time of export and to map the planned end dates separately. This is currently an open item in the SIGs research agenda and contributions on this topic would be welcomed.
There is one exhibit (ID 968) that is entitled “Test Exhibition” and has and end date in the not too distant past (Oct 2020). Is this a real exhibit or an artefact of system testing? If it is a real exhibit then it should be grouped with the other 10 exhibitions with planned end dates (see above). If a system test then I would suggest not exporting it.
E22     ->P16i ->E7 [Exhibition] ->P4 ->E52 ->P82b ->E61 [ExhibEndISODate]
    ->P16.1 ->E55 {Exhibit}
A final note the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by ghost** [comment]
Our database mistakenly calls this table an ISO table. The dates are correct as is, though yes they are not ISO format.

Also in the CB Exhibitions Dataset I'm not seeing this "Text Exhibition" with the ID 968?
