### ISSUE TITLE
CBMAAExhibitions:VenueBeginISODate and VenueEndISODate

### ISSUE THREAD

**Issue by steads** [american-art/cbm#39]
VenueBeginISODate and VenueEndISODate: These are not in ISO format (http://imgs.xkcd.com/comics/iso_8601.png). I do not understand the relationship between these dates and the exhibition dates but it obviously means that there are hidden events that need to be made explicit and their relationship to each other modelled appropriately.

**Comment by ghost** [comment]
So exhibitions can have multiple venues, these fields denote what dates the exhibition was at the venue.

**Comment by steads** [comment]
This means that an exhibition is actually an E7 Activity that has parts consisting of other E7 Activities. Thix can be modelled with P9
