### ISSUE TITLE
PGExhibitions, CBMAAExhibitions: venue date fields and other unused fields

### ISSUE THREAD

**Issue by rhao** [american-art/cbm#4]
What are the VenueBeginISODate and VenueEndISODate fields for? I did not use them for now because I wasn't sure what they meant. I also did not use the DataDate and ExhVenueXrefID fields. Is that acceptable?

**Comment by shanerichey** [comment]
VenueBeginISODate and VenueEndISODate are actually extremely important to exhibition based information. They denote the begin date for a venue of an exhibition and the end date of a venue for the exhibition. ExhVenueXrefID and DataDate are fine to not use.

**Comment by rhao** [comment]
What do you think the best way to model VenueBeginISODate and VenueEndISODate is? Right now I have an E7_Activity that represents the overall exhibition, and that has an E52_Time_Span (the ExhibitionBeginISODate and ExhibitionEndISODate) and an E53_Place (the venue).

**Comment by ghost** [comment]
Modeling the dates as an E52 Timespan as part of the overall exhibition correctly models the function of Venue Begin/End Dates so I agree with their mapping in this regard.
