### ISSUE TITLE
CBMAA versus PG tables

### ISSUE THREAD

**Issue by steads** [american-art/cbm#44]
Shane wrote:-
"These are promised gifts that have not been officially accessioned into our collection. However we want these objects to show up in our data because we exhibit, store, photograph and otherwise manage them as if they were our own. They are separated out because they do not have provenance or accession IDs and when we were preparing data to upload it was easier to make the distinction between the two data sets if we uploaded them as different files. "

The difference is in the provenance data that relates the object to the museum.
CBMAA objects will have had both an instance of E8 Acquisition and an instance of E10 Transfer of Custody relating them (via P22 transferred title to (acquired title through and P29 custody received by (received custody through)) to the instance of E40 Legal Body that is the Crystal Bridges Museum. This may well have been simultaneous in which case it would require multiple instantiation.
PG objects would only have  an instance of E10 Transfer of Custody relating them (via P29 custody received by (received custody through)) to the instance of E40 Legal Body that is the Crystal Bridges Museum.

**Comment by ghost** [comment]
Just to clarify - the difference in terms of what data was provided between CBMAA and PG is:

CBMAA - Provenance and Object Number were included in the dataset

PG - Provenance and Object Number were NOT included in the dataset

This is by design.

**Comment by VladimirAlexiev** [comment]
@JMunro01 I know that CBM is Crystal Bridges Musem.
Could you enlighten me, What is CBMAA and PG? Thanks!

**Comment by ghost** [comment]
Sure Vladimir, CBMAA is our full name (Crystal Bridges Museum of American Art) and the files under that name represent our core permanent collection.

PG stands for Promised Gifts. The museum has a number of gifts which have been promised to us and since they are not in our permanent collection we track them differently and have different fields which we supplied in the data.
