### ISSUE TITLE
Production BOTB and EOTE are not typed.

### ISSUE THREAD

**Issue by workergnome** [american-art/cbm#45]
If I look at, say, http://data.americanartcollaborative.org/page/cbm/object/688/production/date

the dates are literals, but they're untyped.  

I'd strongly recommend that any dates that go into the crm:P82a/b et al be xsd:dateTimes, not strings.  That'll let us consistently do date math with them.  It does mean that they'll have to be munged to actually meet that standard.

**Comment by azaroth42** [comment]
At the very least they need to be the full dateTime format (yyyy-mm-ddThh:mm:ssZ) so they can cast correctly, even if the xsd:dateTime datatype is not explicitly asserted for the literal value.

**Comment by bsnikhila** [comment]
Changed to xsd:date.

**Comment by workergnome** [comment]
The label now no longer makes sense.   It seems to state that this thing was made over the period of a year, rather that it was made at a point sometime within the year.  I'd just leave the label as 1808.

**Comment by bsnikhila** [comment]
Is this only for productions. For actor birth and death dates, the label should be *Start of the year* to *End of the year* right?

**Comment by workergnome** [comment]
I don't think so—that wouldn't make sense.  That would be a  _very_ long birth.

**Comment by bsnikhila** [comment]
Okay, so for both production and birth/death dates, I just leave the label as the year? The Begin of the Begin and End of the End will be typed as xsd:date.

**Comment by workergnome** [comment]
Correct.  THE BOTB/EOTE should be precise xsd:dates, and the label should be the data as provided, so it's OK to be fuzzy there.
