### ISSUE TITLE
Verifying that the data is as expected

### ISSUE THREAD

**Issue by workergnome** [american-art/cbm#46]
When I'm looking at a dimension string, for example [here](http://data.americanartcollaborative.org/page/cbm/object/688/dimensions),  there appear to be two different dimensions given, and there's no space between them.  It's just:

**14 1/2 x 19 1/2 in. (36.8 x 49.5 cm)Framed: 20 3/8 _ 25 3/8 _ 2 1/8 in.**

Just verifying that's as expected?

**Comment by ghost** [comment]
Yea, thats the way it exports from TMS so we'll have to deal I suppose?

**Comment by workergnome** [comment]
No problem at all.  Just wanted to make sure that it wasn't a problem somewhere else in the system.
