### ISSUE TITLE
Dated field is not being modeled

### ISSUE THREAD

**Issue by workergnome** [american-art/cbm#47]
In the Objects field, for example, for [item 688](http://data.americanartcollaborative.org/page/cbm/object/688), the "dated" field is not modeled.  It exists (as **ca. 1813**) and it should be modeled as a display date as shown on [the review site](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_4-search_0).

**Comment by bsnikhila** [comment]
Fixed it.
http://data.crystalbridges.org/object/688/production/date
