### ISSUE TITLE
No current owner

### ISSUE THREAD

**Issue by workergnome** [american-art/cbm#49]
There's no way to know that any work is owned by Crystal Bridges.

Please add [Current Owner](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_16-search_0) to all MMOs

**Comment by ghost** [comment]
I'm confused isn't this implied by how we've separated our datasets into CBMAA and PG? If it's in CBMAA we own it if its in PG its a promised gift to the museum.

**Comment by workergnome** [comment]
@JMunro01—I don't believe that this is a problem in your provided data.  I think that adding the Linked Data statement that says "this artwork is owned by Crystal bridges" was overlooked in the modeling—It's so obvious that it's easy to miss that it needs to be explicitly stated, since we have works owned by many institutions in the Browse app.

**Comment by bsnikhila** [comment]
I have mapped the current owner as CBM only for CBMAA objects. I have not added the Current Owner field to PG objects. Please let me know if I should.

**Comment by workergnome** [comment]
@JMunro01: This is a question for you—I don't think we've thought through the semantics of promised gifts yet.  Do you want to publish them as "Owned" by CBM?  Do we need to come up with something more sophisticated so as to not state things that aren't (yet) true?

**Comment by ghost** [comment]
Great question - they are owned by an anonymous private collection. So the Current Owner should be listed as "Private Collection"

**Comment by workergnome** [comment]
@azaroth42:  Interesting problem here.  Semantically, the museum doesn't own them, it just *has* them.  Do we just indicate custody here, and treat it as a exhibition or loan or a yet-undiscovered AAT term?

**Comment by azaroth42** [comment]
I agree that it's a case of custody. The owner is an Actor (not knowing if it's an individual or an organization) with a label of Anonymous Owner or similar. It shouldn't be "Private Collection", as a collection is not an actor.

Then Anonymous Actor has transferred custody ... not sure we need to model the intent of a promised gift.

**Comment by workergnome** [comment]
The only complication I see is that I need some way to indicate that it should be _grouped_ with the Crystal Bridges stuff.

At least, I think we do?  Are we just treating "Private Collector" as a 15th AAC member?

If not, I need some way to say that this custody is not temporary (i.e. a exhibition loan)...Or I suppose "Private Collector", as part of the Crystal Bridges X-department collection might be enough?

**Comment by ghost** [comment]
I don't know if this will help in the discussion, but they are basically a group of objects not owned by Crystal Bridges, but by a private collector and they are all promised gifts to us. In terms of AAC data, the main difference is that we did not supply provenance data for the promised gift objects.

**Comment by ghost** [comment]
Actually I did some more thinking on it, I think modeling them as loans is most accurate

**Comment by workergnome** [comment]
I agree—they're "long-term loans", and the promise of a gift is probably outside what we need to represent.  It causes some problems for me in the Browse App, in that we hadn't solved how to represent objects that are on loan to an institution, but that's an interesting problem at both the UI level and the mapping level.

@JMunro01: how does the museum refer to the current owner of the work?  We're looking for the  name of the person, group, or legal organization that owns the work. "Private Collector"?  "Private collection"?

@azaroth42:  I might be OK with "private collection", if we think of that as the joint name of am entity that represents a group of people who collect, but I can also understand that it might cause confusion when trying to distinguish between the people who collect and their collection of art.

@bsnikhila:  Do you need assistance with modeling this as a Transfer of Custody?  I would ask that the Event be given a P2_has_type of "Long Term Loan" or "Promised Gift" to make it easy to search for it.  I don't think there's an AAT term for that.

**Comment by azaroth42** [comment]
When the promise comes into effect and it's an actual gift, will the anonymity still be maintained? And if the gifts come in over time, will there need to be two Actors -- one anonymous and one with their actual name?

"Private Collector" seems good to me. I wouldn't be averse to a label of "Private Collection" but an Appellation seems somehow too precise.

**Comment by workergnome** [comment]
Working through this, and other similar issues, I propose that we add:

```ttl
_:work_of_art crm:P46i_forms_part_of <http://data.crystalbridges.org/collection>;
<http://data.crystalbridges.org/collection> a crm:E78_Collection; 
    rdfs:label "The collection of Crystal Bridges Museum of American Art";
    crm:P109_has_current_or_former_curator <http://data.crystalbridges.org>.
```

To every art object in this and every other institution (with the appropriate values, of course).

**Comment by azaroth42** [comment]
:+1:
