### ISSUE TITLE
All titles are mapped as "primary"

### ISSUE THREAD

**Issue by workergnome** [american-art/cbm#50]
If you look at [cbm:2021](http://data.crystalbridges.org/object/2021), you'll see that both titles have P2_has_type to <http://vocab.getty.edu/aat/300404670>.

This should only be used for the primary title, <http://data.americanartcollaborative.org/page/cbm/object/2021/descriptive_title> should not have that type.

**Comment by bsnikhila** [comment]
Fixed it.
http://data.crystalbridges.org/object/2021
