### ISSUE TITLE
Preferred Identifier not modeled

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#53]
[Preferred ID](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_24-search_0) eg for http://data.crystalbridges.org/object/20 shows nothing.
In contrast [Object ID](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_25-search_0) shows "20".
It's rather a pity for an object to have an identifier but not to have a preferred one.
You should assume the Object ID is preferred, and tag it with two AAT concepts:
```turtle
crm:P2_has_type aat:300404621, aat:300404670.
```

**Comment by azaroth42** [comment]
We don't know that's their preferred identifier.  I'd prefer not to assume that it is.

**Comment by VladimirAlexiev** [comment]
Wjhy don't you ask them then?
ISI use it to make up the URL, so ISI does assume it is preferred.

**Comment by bsnikhila** [comment]
The object ID has been mapped as the preferred ID.
