### ISSUE TITLE
Useless name parts

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#55]
http://data.crystalbridges.org/person-institution/111/appellation/middlename doesn't have any useful payload.
Indeed, `LOD CBMAA Constituents.csv` 111 `Eastman Johnson` has no middle name.
In such case you should skip the node and the incoming triple
`cbm:person-institution/111/appellation crm:P106_is_composed_of cbm:person-institution/111/appellation/middlename`
rather than making a useless node.

The same may apply to any other name part (eg missing firstname or lastname)

**Comment by bsnikhila** [comment]
Fixed it. 
http://data.crystalbridges.org/constituent/111/name_composition has only first name and last name

**Comment by VladimirAlexiev** [comment]
http://data.americanartcollaborative.org/page/cbm/constituent/1015/name_composition is empty. 
However, this will get fixed when you move its statements to http://data.americanartcollaborative.org/page/cbm/constituent/1015/name, as @workergnome noted in the other issue.
