### ISSUE TITLE
Missing AlphaSort

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#56]
`LOD CBMAA Constituents.csv` 1083 has AlphaSort "Rogers, Daniel" in the source data.
But this is missing in RDF: http://data.americanartcollaborative.org/page/cbm/person-institution/1083.
In contrast, it's present for constituent 111: http://data.americanartcollaborative.org/page/cbm/person-institution/111/appellation_alpha_sort

**Comment by bsnikhila** [comment]
This has been fixed. It is now found at http://data.crystalbridges.org/constituent/1083 and http://data.crystalbridges.org/constituent/111

**Comment by VladimirAlexiev** [comment]
Note to self: base is changed from `person-institution` to `constituent`. Checked for http://data.crystalbridges.org/constituent/1083 on "review"
