### ISSUE TITLE
Missing name parts

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#57]
In continuation of #56: http://data.americanartcollaborative.org/page/cbm/person-institution/1083/appellation has 3 name part URLs that lead nowhere. As a result, this constituent does not have any appellation

**Comment by VladimirAlexiev** [comment]
This node has label "Daniel Rogers" so I wonder why the name parts are missing

**Comment by bsnikhila** [comment]
This has been fixed. It is found at http://data.crystalbridges.org/constituent/1083

**Comment by workergnome** [comment]
This is close, but it currently says that a valueless name is composed of "Daniel" and "Rogers".  Instead, it should say that the appellation "Daniel Rogers" (http://data.americanartcollaborative.org/page/cbm/constituent/1083/name) is composed of "Daniel" and "Rogers

**Comment by VladimirAlexiev** [comment]
exactly!

**Comment by bsnikhila** [comment]
Can you please tell me if it is fine now?

**Comment by workergnome** [comment]
Looks good.
