### ISSUE TITLE
CBM Title mapping

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#58]
`LOD CBMAA Titles.csv` includes eg this record:
```
ObjectID=     197
TitleID=      6,716  (someone printed the ID with a decimal separator, silly)
Title=        From "Album Unique" formerly in the collection of the Duke of Portland
TitleTypeID=  4
TitleType=    Group Title
DisplayOrder= 2
DataDate=     12/23/2015
```

It's converted to this (see http://data.americanartcollaborative.org/page/cbm/object/197/)
```turtle
cbm:object/197 crm:P102_has_title cbm:object/197/group_title,
  cbm:object/197/primary_title, cbm:object/197/unknown_title_type.

cbm:object/197/group_title a crm:E35_Title;
  crm:P1_is_identified_by cbm:object/197/group_title/id;
  crm:P2_has_type	cbm:object/197/title_type, 
    aat:300404670; # preferred name
  rdf:value 'From "Album Unique" formerly in the collection of the Duke of Portland'.

cbm:object/197/title_type a crm:E55_Type;
  skos:prefLabel "Group Title", "Primary Title".

cbm:object/197/group_title/id a crm:E42_Identifier
  crm:P2_has_type	aat:300404012; # unique identifier
  rdf:value "6,716".
```

This mapping is badly botched. It has the following problems:

1. It uses TitleType in the title URL. But one object may have several titles of the same type, eg 
```sh
perl -pe 's{^(\d+).*,(\w+ Title|\(not entered\)),.*$}{$1\t$2}' "PG_Titles/LOD PG Titles.csv"|sort|uniq -d
45      Alternate Title
```
  Object 45 has 3 Alternate Titles, so the result is this mixup you see at   http://data.americanartcollaborative.org/page/cbm/object/45/alternate_title (1 title with 3 values).
  Instead of TitleType, you should use TitleID in the URL

2. The title type uses per-object URL cbm:object/197/title_type. This has 2 undesired consequences:
  - All titles of an object get all title types. Eg #50 complains that all titles become Primary Title (because all objects have such), and above you see both "Group Title" and "Primary Title"
  - The title types across objects use different nodes, so the fact that eg "Group Title" means the same across objects is not captured.
  So instead, you should use a per-museum (not per-object) URL and use TitleType, eg:
```turtle
cbm:title/group_title a crm:E55_Type;
  skos:prefLabel "Group Title"
```

3. There is no need to tag cbm:object/197/group_title/id with aat:300404012 # unique identifier because see next.
4. Use crm:P48_has_preferred_identifier instead of crm:P1_is_identified_by.
5. aat:300404670 "preferred name" doesn't reflect the nature of the title (how is a Group Title a Preferred Name???), so remove it

**Comment by bsnikhila** [comment]
Changed the URIs to use Title IDs.
