### ISSUE TITLE
(!) wasteful multiplicity of type nodes

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#59]
Consider this:
```ttl
cbm:person-institution/111/appellation/firstname a crm:E82_Actor_Appellation;
  crm:P2_has_type cbm:person-institution/111/appellation/name_type/firstname
  rdf:value "George".
cbm:person-institution/111/appellation/name_type/firstname a crm:E55_Type;
  skos:broadMatch aat:300404651; # first name
  skos:prefLabel "First Name".
```
The node cbm:person-institution/111/appellation/name_type/firstname is useless because it doesn't say anything more than aat:300404651; # first name. But this is according to the mapping: presumably it gives museums the freedom to have their own concept for First Name, not that such freedom is needed or desired.

The problem is that you use a separate node for EVERY instance of a first name. Instead, use a single node eg `cbm:type/name/firstname`

**Comment by VladimirAlexiev** [comment]
This probably applies to all museums, does apply to all Constituent name types, and probably to other type nodes as well (eg title types, see #58 item 2)

**Comment by workergnome** [comment]
I agree—the reification of having both a type and a broadMatch is unnecessary, and should eventually be corrected in the model.  If possible, we should fix this in all mappings, however I don't want to break things that are already modeled by changing the review tool midstream, and if ISI isn't going to be able to correct the reification, we should leave it and fix it in a future phase.

This does not change the fact that 

> The problem is that you use a separate node for EVERY instance of a first name. Instead, use a single node eg cbm:type/name/firstname

is a serious problem, and needs to be addressed.

**Comment by bsnikhila** [comment]
I have changed the name type nodes to thesauri/name_type/first_name thesauri/name_type/middle_name and thesauri/name_type/last_name

**Comment by VladimirAlexiev** [comment]
@bsnikhila did you check it for other types and other museums as well?

**Comment by bsnikhila** [comment]
I will do that.
