### ISSUE TITLE
useless per-object exhibition_event

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#60]
http://data.americanartcollaborative.org/page/cbm/object/108
```ttl
cbm:object/108 crm:P12i_was_present_at cbm:exhibition/10, cbm:exhibition/86,
   cbm:object/108/exhibition_event.
```
Then that http://data.americanartcollaborative.org/page/cbm/object/108/exhibition_event says it's an Event and it has an Appellation.
The appellation http://data.americanartcollaborative.org/page/cbm/object/108/exhibition_event/appellation says it's an Appellation, it's a "preferred name" (useless)... but **does not provide** the name.

So the whole construct is useless. Delete these triples starting from 
`crm:P12i_was_present_at cbm:object/108/exhibition_event`

**Comment by bsnikhila** [comment]
We are anyway not mapping exhibitions for any museum as of now. So I will remove this.

**Comment by VladimirAlexiev** [comment]
Do remove `cbm:object/108/exhibition_event` but leave the others.
   
@workergnome @azaroth42 the app will not be displaying Exhibitions?!?
I see most museums have mapped them (as Event with a string, no structured info).
As a minimum, p2 must be added: https://github.com/american-art/npg/issues/5
