### ISSUE TITLE
(!) missing bibliographic references

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#61]
`LOD CBMAA Bibliography.csv` and `LOD PG Bibliography.csv` have bibliographic references.
Eg obj=20 is documented in ref=207 "Crystal Bridges Member Magazine Fall/Winter 2012".
I assume that `E31_Document1 P70_documents E22_Man-Made_Object1` at the top of the mapping expresses that.
However, when I try [this query](http://yasgui.org/#query=PREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0Aselect+*+%7B%0A++%3Fx+crm%3AP70_documents+%3Fy%0A%7D&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=http%3A%2F%2Fdata.americanartcollaborative.org%2Fsparql&requestMethod=GET&tabTitle=Query&headers=%7B%7D&outputFormat=table) at yasgui:
```sparql
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
select * {
  ?x crm:P70_documents ?y
}
```
I get only Autry references and objects (67). So this affects all museums but Autry

**Comment by VladimirAlexiev** [comment]
http://data.americanartcollaborative.org/page/cbm/object/20 has
`crm:P129i_is_subject_of	cbm:object/20/bibliography, cbm:object/20/provenance`
Both of these are Linguistic Objects with just a text (no type), so there's no way to tell which is which.

**Comment by bsnikhila** [comment]
We are not mapping Bibliography for any museum as of now. It will be done in the future.

**Comment by bsnikhila** [comment]
I will anyway remove the crm:P129i_is_subject_of cbm:object/20/bibliography

**Comment by VladimirAlexiev** [comment]
@workergnome @azaroth42 What is this tendency to drop data? 
https://github.com/american-art/cbm/issues/60#issuecomment-282373260 says exhibitions are out, and https://github.com/american-art/cbm/issues/61#issuecomment-282372851 says bibliographies are out?
Who makes these decisions??

[Catalogue Raisonné](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_31-search_0) is mapped, so why would other Bibliographic references be removed?

**Comment by workergnome** [comment]
The decisions of which sections of data to drop were made by Eleanor and @caknoblock to ensure that ISI would be able to complete mapping of all the institutions within their scope of work.

**Comment by azaroth42** [comment]
:+1: Propose close.

**Comment by workergnome** [comment]
😞 Agree.  As much as I'd like this data to exist, it'll need to be revisited in future phases.

**Comment by VladimirAlexiev** [comment]
Well, ok
