### ISSUE TITLE
Website and Image are not mapped

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#62]
`LOD CBMAA Image URLs.csv` has eg this: 
`22, collection.crystalbridges.org/objects/22, collection.crystalbridges.org/objects/fullimage/22`

If you put http://data.crystalbridges.org/object/22 in the [Website mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_28-search_0), it finds no data. But http://collection.crystalbridges.org/objects/22 is in fact the website for that painting.

Unfortunately collection.crystalbridges.org/objects/fullimage/22 returns
`An exception has occurred. The view type “fullimage” is invalid`
The image URL for that one is http://collection.crystalbridges.org/internal/media/dispatcher/2066/resize%3Aformat%3Dfull
but I don't see a way to compute it from the one in the source data. @jmunro01 can you help?

**Comment by ghost** [comment]
Yea so we put dummy URLs in for the full size images because we're having some trouble getting stable full size image URLs out of eMuseum. We tried doing it through the eMuseum API, but no dice so far on that front. I should have more news on this next week when I have a call about it.

**Comment by VladimirAlexiev** [comment]
@JMunro01 AAC doesnt' necessarily need full images, but SOME images it needs

**Comment by bsnikhila** [comment]
The given website and image URLs have been mapped.

**Comment by VladimirAlexiev** [comment]
- website: checked objects 22, 23, 73, all is ok
- image: checked a few, they got image URL like http://collection.crystalbridges.org/objects/fullimage/22 but CBM's site returns nothing for it

Pulled from github: `LOD CBMAA Image URLs_with_header.csv, LOD PG Image URLs_with_header.csv` do state these URLs. @JMunro01 is it possible to set redirects on your site to return images for these URLs? Otherwise, can you export the working URLs, eg http://collection.crystalbridges.org/internal/media/dispatcher/2066/resize:format=full

**Comment by ghost** [comment]
Yea so like I said none of the URL's for full images are working I just threw in dummy URLs. And yea http://collection.crystalbridges.org/internal/media/dispatcher/2066/resize:format=full work's as a URL for the image, but in order for me to dump out those URLs I need to know which ID pertaining to the object 2066 is and I haven't been able to figure that out yet. It's definitely not the ObjectID (if so this would be super easy).

I've contacted the support team for our database hoping to get some answers.

I'll also need to fix any of our object record page URLs, the standard is collection.crystalbridges.org/objects/534
Where 534 = ObjectID, however in the export at some point in the process a comma got added to anything with object ID > 999.

**Comment by VladimirAlexiev** [comment]
@JMunro01 that last thing is ok: http://data.americanartcollaborative.org/page/cbm/object/5909 has foaf:homepage 
http://collection.crystalbridges.org/objects/5909 (not "5,909") and that link opens ok.

Hoping your support team can find the table where it says 22->2066 ! cheers

**Comment by ghost** [comment]
So I found the rogue ID that's in our full image URLs and I have the updated CSVs. The repository won't let me upload the files, would be happy to email them to someone who can! Turns out it lives in a xref table between the Media and Objects tables, not in the Media table!

**Comment by caknoblock** [comment]
Shane has write access to the CBM repository.  You can also send me your Github ID and I can give you write access.  Or you can just fork the repository and do a pull request.  I would like to stay away from emailing files.

**Comment by ghost** [comment]
Ok cool, thanks Craig, my ID is 17013881 I believe.

**Comment by caknoblock** [comment]
Sorry, that’s not a valid GitHub id.  Why don’t you ask Shane to upload the documents.

**Comment by ghost** [comment]
Sure 10-4

**Comment by VladimirAlexiev** [comment]
Are the updated image URLs uploaded on github?
I checked eg http://browse.americanartcollaborative.org/object/cbm/20109613.html and it still shows a broken image eg http://collection.crystalbridges.org/objects/fullimage/1645

@caknoblock, the github id of @JMunro01 is very obviously "JMunro01"

**Comment by shanerichey** [comment]
Vladimir,

I made an attempt to upload them a few months ago, but I guess I didn't get
them in the correct place. I had the same problem with uploading the
original files. I have the file here on my desktop should I try to
re-upload it to GitHub?

**Comment by shanerichey** [comment]
I just re-uploaded two files, I wasn't sure where you wanted them, so they're both in the main directory.

CBMAA Image URLs v3.csv
PG Image URLs v3.csv

**Comment by caknoblock** [comment]
Shane, I just reviewed your files and there are two issues.  First, you have multiple images for the same object ID.  I would expect there to be exactly one image per object.  I checked and these are images of completely different paintings.   Second, we need a header for each of your data files.  If you look in the directory: CBMAA_URLs, you will see an example of the file with the correct header that we need for processing.  You can place your updated files into the appropriate URL directories.  These are labelled CBMAA_URLs and PG_URLs.  You can post here once the issues have been resolved and we can reload the data.

**Comment by ghost** [comment]
So I'm working on why the URL's aren't giving the right ID and I'll fix the header, but I discovered something that might be an issue might not be: a large number of the records we are turning over do not have images hosted on our online art collection. This is generally because the photography we have is not our photography and as such there are copyright issues. I originally thought it'd be only a few, but looking at the dataset it'd be probably around 800 records.

The report I made to generate URLs will generate URLs regardless whether the URLs will resolve online, is that fine that there'd be a lot of garbage URLs that'll just 404?

**Comment by caknoblock** [comment]
Generating bad URLs will create a poor experience for the users.  Much better if you can just not report a URL for an object if you cannot provide one.  Can you run a process that checks the URLs and removes the ones that return a 404?

**Comment by kateblanch** [comment]
Jeremy, ping me offline and I could help you use conditional logic in your report to insert a blank instead of a URL. Just think about what condition / logic (when this object has "restricted" checkbox checked then...) would fit the task.

**Comment by VladimirAlexiev** [comment]
Or else I can write some script to check them with curl and remove the broken ones
