### ISSUE TITLE
Creation display date is missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#63]
`LOD CBMAA Objects_formatted.csv` obj=5366 field=Dated is "1966, repainted 1969-1970".
This useful info (display date) is missing from http://data.crystalbridges.org/object/5366/production/date.

The [Creation date mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_4-search_0) specifies `display_date`

**Comment by bsnikhila** [comment]
Fixed it. DisplayDate is now included.

**Comment by VladimirAlexiev** [comment]
Checked
