### ISSUE TITLE
creation dates don't have datatype

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#64]
The structured creation dates `DateBegin DateEnd` should have a datatype (in this case `xsd:gYear`).
If other museums provide greater resolution, they should use `xsd:gYearMonth` or `xsd:date` respectively. Such datatypes are needed for efficient comparison (so the repo knows to index them properly).

Note: the [Creation date mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_4-search_0) doesn't specify datatypes for `earliest_date latest_date`.

**Comment by workergnome** [comment]
It's definitely a limitation of the review tool that there's not an easy way to specify types for literals. 

I think it's worth having a discussion of how to apply data types to dates—they definitely need them, and they're currently a mess.  I know @azaroth42 suggested that everything should be a `xsd:dateTime` regardless, and I've been trying to figure out how to record variant precisions of dates using CIDOC-CRM, xsd, and/or EDTF.

**Comment by VladimirAlexiev** [comment]
This decision should be in line with what repos support. 
- No repos implement other than XSD types (AFAIK)
- SPARQL 1.1 only mandates xsd:dateTime comparisons
- many repos (eg GraphDB) also implement xsd:date comparisons. 

So you could represent it eg like this:
```ttl
<date1> a crm:E52_Time-Span;
  rdfs:label "2017";
  crm:P82a_begin_of_the_begin "2017-01-01"^^xsd:date;
  crm:P82b_end_of_the_end     "2017-12-31"^^xsd:date.

<date2> a crm:E52_Time-Span;
  rdfs:label "Feb 2017";
  crm:P82a_begin_of_the_begin "2017-02-01"^^xsd:date;
  crm:P82b_end_of_the_end     "2017-02-28"^^xsd:date.

<date2> a crm:E52_Time-Span;
  rdfs:label "between May 2016 and Feb 2017";
  crm:P82a_begin_of_the_begin "2016-05-01"^^xsd:date;
  crm:P82b_end_of_the_end     "2017-02-28"^^xsd:date.
```
Of course, the latest date must be an accurate end-day of the respective month.

**Comment by VladimirAlexiev** [comment]
@caknoblock can you comment what is supported by the repository

**Comment by caknoblock** [comment]
We are running Apache Jena Fuseki 2 for the triplestore.

**Comment by VladimirAlexiev** [comment]
And do you know which date-related datatypes it supports for efficient comparability?
Sparql only mandates comparability of full xsd:dateTime: https://www.w3.org/TR/sparql11-query/#OperatorMapping.

Of course, the XSD format is such that years 0001 to 9999 will compare correctly even if string comparison is used. But it may not be as efficient as having a special literal index.

**Comment by bsnikhila** [comment]
Changed them to xsd:date.
