### ISSUE TITLE
"unknown title type" repeats the defined title types

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#65]
Consider http://data.americanartcollaborative.org/page/cbm/object/197/unknown_title_type.
It repeats the values of the defined title types:
- http://data.crystalbridges.org/object/197/primary_title
- http://data.crystalbridges.org/object/197/group_title

**Comment by workergnome** [comment]
Is this still valid, @bsnikhila?  I can't get to that URL—you might have fixed it, in which case can you close this issue?

**Comment by bsnikhila** [comment]
Yes, I have fixed this.
We now have 
http://data.crystalbridges.org/object/197/primary_title for the primary title
and http://data.crystalbridges.org/object/197/alt_title for the alternate title

**Comment by VladimirAlexiev** [comment]
Why do you use "alt_title" in the URL of the "group title"?
See https://github.com/american-art/cbm/issues/58 item 1: do not use the title type in the title URL, use the title ID. 
See "LOD PG Titles.csv": object 45 has two "Alternate Title", so you cannot base the title URL on title type.

**Comment by bsnikhila** [comment]
A few museums don't have the Title ID. So we were using the title itself in the URI for the primary title and "alt_title"(or something similar) for alternate titles. Do you want me to use the ID when it is provided, and use the title itself in the URI when the ID is not provided?

Also related to https://github.com/american-art/npg/issues/67

**Comment by VladimirAlexiev** [comment]
If they have potentially multiple titles with the same type, you must ask them to export the ID.
