### ISSUE TITLE
XXX and YYY don't look like real people

### ISSUE THREAD

**Issue by workergnome** [american-art/cbm#66]
Any idea what http://data.americanartcollaborative.org/page/cbm/xxx or http://data.americanartcollaborative.org/page/cbm/yyy are?

**Comment by bsnikhila** [comment]
Yes. That was used for experimental purposes. We were having a bug and we used "xxx" and "yyy" for testing. It will be removed soon.

**Comment by workergnome** [comment]
Thanks.  Feel free to close this when they're gone.

**Comment by bsnikhila** [comment]
Done. Removed it.
