### ISSUE TITLE
CBM Constituent ID

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#69]
CBM Constituent ID is not mapped.
Eg http://data.americanartcollaborative.org/page/cbm/constituent/1067 should have P1 with value "1067".
@workergnome needs it for the app

**Comment by bsnikhila** [comment]
Added.

**Comment by workergnome** [comment]
Can you add the AAT "preferred term" type to this?

**Comment by bsnikhila** [comment]
Added.
