### ISSUE TITLE
IMPORTANT missing titles for title type (not entered)

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/cbm#70]
CBM has some titles with type=0 "(not entered)"
```sh
grep ",0," *Title*/*.csv|head -10
# file:ObjectID,TitleID,Title,TitleTypeID,TitleType,DisplayOrder,DataDate
CBMAA_Titles/LOD CBMAA Titles.csv:1190,"1,222",Untitled,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1220,"1,252",Cooper Square,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1491,"1,574",Humble Birth,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1492,"1,575",Cube,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1494,"1,577",Untitled,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1499,"1,583",The Family,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1500,"1,584",Out Chorus,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1502,"1,586",People in Other Rooms (Harlem Street Scene),0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1503,"1,587",Revolt on the Amistad,0,(not entered),1,12/23/2015
CBMAA_Titles/LOD CBMAA Titles.csv:1504,"1,588",Harriet,0,(not entered),1,12/23/2015
```
I checked the first 3 objects (eg http://data.americanartcollaborative.org/page/cbm/object/1492) and they **don't have any title**. Please map all titles: that is a crucial piece of info.

@workergnome we saw in the demo yesterday plenty of objects with no title, perhaps this is part of the reason why.

**Comment by bsnikhila** [comment]
I added them. Can you please check and let me know if it's alright?

**Comment by VladimirAlexiev** [comment]
@bsnikhila  Checked a few, the title is there, but:
1. It's better to use TitleID in the URL, not the title words. Else you may get conflicts with titles of other objects that have a type.
2. According to [the model](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_0-search_0), you also need to emit the title string as rdfs:label on the object

Cheers!

**Comment by bsnikhila** [comment]
Changed the URIs to use Title IDs.
