### ISSUE TITLE
Removal of Zeroes in Object Numbers

### ISSUE THREAD

**Issue by ghost** [american-art/cbm#74]
If you look at http://browse.americanartcollaborative.org/object/cbm/20112.html

The Object # is listed as 2011.2 - this is incorrect - the Object # is 2011.20.

At some point in the process those end zeroes are being removed. I looked at the raw data on GitHub and (I'm a novice), but it looks like the URI for Object Number is doing it. I can tell because the Object ID is the same but the Object Number is wrong. 

<http://data.crystalbridges.org/object/1584/obj_no>
  <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "2011.2" .

ObjectID 1530 is the Object with Object Number 2011.2

<http://data.crystalbridges.org/object/1530/obj_no>
  <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "2011.2" .

**Comment by bsnikhila** [comment]
This seems to be an issue with the way the data is exported itself. If we see the [data file](https://github.com/american-art/cbm/blob/master/CBMAA_Objects/LOD%20CBMAA%20Objects_formatted.csv) on github, we see that the object number field for both the objects seem to have the same object number 2011.2.

**Comment by kateblanch** [comment]
It looks like @bsnikhila might be referencing out dated data. The newest version (in the LOD v2 folder) has the 0's present for object id 1584. 
https://github.com/american-art/cbm/tree/master/CBMAA%20LOD%20v2

Is this a refresh issue?

**Comment by bsnikhila** [comment]
Fixed it.
