### ISSUE TITLE
Dimension Display

### ISSUE THREAD

**Issue by ghost** [american-art/cbm#76]
If you look at http://browse.americanartcollaborative.org/object/cbm/20112.html

Dimensions are displaying with underscores instead of "x."

18 1/2 _ 12 1/4 in. (47 _ 31.1 cm)Framed: 24 1/2 _ 18 1/4 _ 2 1/4 in.

I looked at the data I provided and the "x" is still present, so I don't know where in the process this is happening.

**Comment by workergnome** [comment]
This appears to be fixed.
