### ISSUE TITLE
CBMAAObjects:ObjectNumber

### ISSUE THREAD

**Issue by steads** [american-art/cbm#8]
ObjectNumber: This does not seem to have a mapping. It would seem to be a very important field as it looks like the primary identifier for the artwork and so would form an important access point for integration. E22-> P48 has preferred identifier (is preferred identifier of): E42 Identifier

**Comment by ghost** [comment]
Agreed. ObjectNumber needs to be mapped to the data.

**Comment by VladimirAlexiev** [comment]
Same as #48
