### ISSUE TITLE
CBMAAObjects:Dated

### ISSUE THREAD

**Issue by steads** [american-art/cbm#9]
Dated: This seems to be an E62 String containing a textual statement about the production of the object in the collection. If the resources for a full analysis are available then more meaning might be extracted from the content of this field. If not then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Production Date Statement}

**Comment by ghost** [comment]
There are three fields for objects involving Dates - Dated, DateBegin, and DateEnd. DateBegin and DateEnd are the search dates. Dated is, as you say a textual statement about production. It contains qualifiers like circa.
